// Generated by andromda-angular cartridge (service\service.impl.ts.vsl) CAN EDIT
import { Injectable, inject } from '@angular/core';
import { Observable } from 'rxjs';
import { PolicyVO } from '@app/model/bw/co/roguesystems/imis/policy/policy-vo';
import { HttpClient } from '@angular/common/http';
import { Page } from '@app/model/page.model';
import { SearchObject } from '@app/model/search-object';

@Injectable({
  providedIn: 'root'
})
export class PolicyApi {
    
    protected path = '/policy';

    private http = inject(HttpClient);

    public findById(id: number | any ): Observable<PolicyVO | any> {


        return this.http.get<PolicyVO | any>(this.path + `/${id}`);

    }

    public getAll(): Observable<PolicyVO[] | any[]> {


        return this.http.get<PolicyVO[] | any[]>(this.path);

    }

    public remove(id: number | any ): Observable<boolean | any> {


        return this.http.delete<boolean | any>(this.path + `/${id}`);

    }

    public save(type: PolicyVO | any ): Observable<PolicyVO | any> {


        return this.http.post<PolicyVO | any>(this.path, type);

    }

    public search(criteria: string | any ): Observable<PolicyVO[] | any[]> {


        return this.http.post<PolicyVO[] | any[]>(this.path + `/search?criteria=${criteria}`, criteria);

    }

}
