// Generated by andromda-angular cartridge (controller\controller.impl.ts.vsl) Can Modify
import { Injectable } from '@angular/core';
import { RelationshipController } from '@app/controller/relationship/relationship-controller';

@Injectable()
export class RelationshipControllerImpl extends RelationshipController {

    constructor() {
        super();
    }

}
