// Generated by hibernate/SpringHibernateDaoImpl.vsl in andromda-spring-cartridge on $springUtils.date.
// license-header java merge-point
/**
 * This is only generated once! It will never be overwritten.
 * You can (and have to!) safely modify it by hand.
 */
package bw.co.roguesystems.imis.relationship;

import org.springframework.stereotype.Repository;

/**
 * @see Relationship
 */
@Repository("relationshipDao")
public class RelationshipDaoImpl
    extends RelationshipDaoBase
{
    
    public RelationshipDaoImpl(
        RelationshipRepository relationshipRepository
    ) {

        super(
            relationshipRepository
        );
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public void toRelationshipVO(
        Relationship source,
        RelationshipVO target)
    {
        // TODO verify behavior of toRelationshipVO
        super.toRelationshipVO(source, target);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RelationshipVO toRelationshipVO(final Relationship entity)
    {
        // TODO verify behavior of toRelationshipVO
        return super.toRelationshipVO(entity);
    }

    /**
     * Retrieves the entity object that is associated with the specified value object
     * from the object store. If no such entity object exists in the object store,
     * a new, blank entity is created
     */
    private Relationship loadRelationshipFromRelationshipVO(RelationshipVO relationshipVO)
    {
        if (relationshipVO.getId() == null)
        {
            return  Relationship.Factory.newInstance();
        }
        else
        {
            return this.load(relationshipVO.getId());
        }
        
    }

    /**
     * {@inheritDoc}
     */
    public Relationship relationshipVOToEntity(RelationshipVO relationshipVO)
    {
        // TODO verify behavior of relationshipVOToEntity
        Relationship entity = this.loadRelationshipFromRelationshipVO(relationshipVO);
        this.relationshipVOToEntity(relationshipVO, entity, true);
        return entity;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public void relationshipVOToEntity(
        RelationshipVO source,
        Relationship target,
        boolean copyIfNull)
    {
        // TODO verify behavior of relationshipVOToEntity
        super.relationshipVOToEntity(source, target, copyIfNull);
    }
}