// Generated by andromda-angular cartridge (view\view.component.imp.ts.vsl) CAN EDIT!
import { Component } from '@angular/core';
import { BenefitViewComponent } from '@app/view/policy/type/benefits/benefit-view.component';
import { BenefitViewVarsForm } from '@app/view/policy/type/benefits/benefit-view.component';
import { MatRadioChange } from '@angular/material/radio';
import { MatCheckboxChange } from '@angular/material/checkbox';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { TranslateModule } from '@ngx-translate/core';
import { MaterialModule } from '@app/material.module';
import { CsvModule } from '@ctrl/ngx-csv';
import { TableComponent } from '@app/components/table/table.component';
import { BenefitEditorImplComponent } from '@app/components/policy/type/benefits/benefit-editor-impl.component';
import { BenefitDetailsImplComponent } from '@app/components/policy/type/benefits/benefit-details-impl.component';

@Component({
  selector: 'app-benefit-view',
  templateUrl: './benefit-view.component.html',
  styleUrls: ['./benefit-view.component.scss'],
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    TranslateModule,
    MaterialModule,
    CsvModule,
    TableComponent,
    BenefitEditorImplComponent,
    BenefitDetailsImplComponent
  ],
})
export class BenefitViewImplComponent extends BenefitViewComponent {

    constructor() {
        super();
        this.benefitApiStore.reset()
        this.success = this.benefitApiStore.success;
        this.loading = this.benefitApiStore.loading;
        this.error = this.benefitApiStore.error;
        this.messages = this.benefitApiStore.messages;

        this.route.queryParams.subscribe((params: any) => {
          if (params.id) {
            this.benefitApiStore.findById(params);
          }
        });
    }

    override beforeOnInit(form: BenefitViewVarsForm): BenefitViewVarsForm{     
        return form;
    }

    doNgOnDestroy(): void {
    }
}