// Generated by andromda-angular cartridge (view\view.component.imp.ts.vsl) CAN EDIT!
import { Component } from '@angular/core';
import { EditBenefitComponent } from '@app/view/policy/type/benefits/edit-benefit.component';
import { EditBenefitVarsForm } from '@app/view/policy/type/benefits/edit-benefit.component';
import { MatRadioChange } from '@angular/material/radio';
import { MatCheckboxChange } from '@angular/material/checkbox';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { TranslateModule } from '@ngx-translate/core';
import { MaterialModule } from '@app/material.module';
import { CsvModule } from '@ctrl/ngx-csv';
import { TableComponent } from '@app/components/table/table.component';
import { BenefitDetailsImplComponent } from '@app/components/policy/type/benefits/benefit-details-impl.component';
import { BenefitEditorImplComponent } from '@app/components/policy/type/benefits/benefit-editor-impl.component';

@Component({
  selector: 'app-edit-benefit',
  templateUrl: './edit-benefit.component.html',
  styleUrls: ['./edit-benefit.component.scss'],
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    TranslateModule,
    MaterialModule,
    CsvModule,
    TableComponent,
    BenefitDetailsImplComponent,
    BenefitEditorImplComponent,
  ],
})
export class EditBenefitImplComponent extends EditBenefitComponent {

    constructor() {
        super();
        this.benefitApiStore.reset()
        this.success = this.benefitApiStore.success;
        this.loading = this.benefitApiStore.loading;
        this.error = this.benefitApiStore.error;
    }

    override beforeOnInit(form: EditBenefitVarsForm): EditBenefitVarsForm{     
        return form;
    }

    doNgOnDestroy(): void {
    }

    override beforeEditBenefitSave(form: any): void {
        
      form.benefit = { ...this.benefitEditor?.benefitEditorForm?.value }
      this.benefitApiStore.save(form);
    }
}