// Generated by andromda-angular cartridge (view\view.component.imp.ts.vsl) CAN EDIT!
import { Component } from '@angular/core';
import { EditBeneficiaryComponent } from '@app/view/policy/type/benefits/edit-beneficiary.component';
import { EditBeneficiaryVarsForm } from '@app/view/policy/type/benefits/edit-beneficiary.component';
import { MatRadioChange } from '@angular/material/radio';
import { MatCheckboxChange } from '@angular/material/checkbox';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { TranslateModule } from '@ngx-translate/core';
import { MaterialModule } from '@app/material.module';
import { CsvModule } from '@ctrl/ngx-csv';
import { TableComponent } from '@app/components/table/table.component';
import { SharedModule } from '@app/@shared';
import { BenefitDetailsImplComponent } from '@app/components/policy/type/benefits/benefit-details-impl.component';
import { BenefitEditorImplComponent } from '@app/components/policy/type/benefits/benefit-editor-impl.component';

@Component({
  selector: 'app-edit-beneficiary',
  templateUrl: './edit-beneficiary.component.html',
  styleUrls: ['./edit-beneficiary.component.scss'],
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    TranslateModule,
    SharedModule,
    MaterialModule,
    CsvModule,
    TableComponent,
    BenefitDetailsImplComponent,
    BenefitEditorImplComponent,
  ],
})
export class EditBeneficiaryImplComponent extends EditBeneficiaryComponent {

    constructor() {
        super();
    }

    override beforeOnInit(form: EditBeneficiaryVarsForm): EditBeneficiaryVarsForm{     
        return form;
    }

    doNgOnDestroy(): void {
    }
}