// Generated by andromda-angular cartridge (service\service.impl.ts.vsl) CAN EDIT
import { Injectable, inject } from '@angular/core';
import { Observable } from 'rxjs';
import { BenefitVO } from '@app/model/bw/co/roguesystems/imis/policy/type/benefits/benefit-vo';
import { HttpClient } from '@angular/common/http';
import { Page } from '@app/model/page.model';
import { SearchObject } from '@app/model/search-object';

@Injectable({
  providedIn: 'root'
})
export class BenefitApi {
    
    protected path = '/policy/type/benefit';

    private http = inject(HttpClient);

    public findById(id: number | any ): Observable<BenefitVO | any> {


        return this.http.get<BenefitVO | any>(this.path + `/${id}`);

    }

    public getAll(): Observable<BenefitVO[] | any[]> {


        return this.http.get<BenefitVO[] | any[]>(this.path);

    }

    public remove(id: number | any ): Observable<boolean | any> {


        return this.http.delete<boolean | any>(this.path + `/${id}`);

    }

    public save(benefit: BenefitVO | any ): Observable<BenefitVO | any> {


        return this.http.post<BenefitVO | any>(this.path, benefit);

    }

    public search(criteria: string | any ): Observable<BenefitVO[] | any[]> {


        return this.http.post<BenefitVO[] | any[]>(this.path + `/search?criteria=${criteria}`, criteria);

    }

}
