// Generated by andromda-angular cartridge (service\service.impl.ts.vsl) CAN EDIT
import { Injectable, inject } from '@angular/core';
import { Observable } from 'rxjs';
import { BeneficiaryVO } from '@app/model/bw/co/roguesystems/imis/policy/beneficiary/beneficiary-vo';
import { HttpClient } from '@angular/common/http';
import { Page } from '@app/model/page.model';
import { SearchObject } from '@app/model/search-object';

@Injectable({
  providedIn: 'root'
})
export class BeneficiaryApi {
    
    protected path = '/policy/beneficiary';

    private http = inject(HttpClient);

    public findById(id: number | any ): Observable<BeneficiaryVO | any> {


        return this.http.get<BeneficiaryVO | any>(this.path + `/${id}`);

    }

    public getAll(): Observable<BeneficiaryVO[] | any[]> {


        return this.http.get<BeneficiaryVO[] | any[]>(this.path);

    }

    public remove(id: number | any ): Observable<boolean | any> {


        return this.http.delete<boolean | any>(this.path + `/${id}`);

    }

    public save(benefit: BeneficiaryVO | any ): Observable<BeneficiaryVO | any> {


        return this.http.post<BeneficiaryVO | any>(this.path, benefit);

    }

    public search(criteria: string | any ): Observable<BeneficiaryVO[] | any[]> {


        return this.http.post<BeneficiaryVO[] | any[]>(this.path + `/search?criteria=${criteria}`, criteria);

    }

}
