// Generated by andromda-angular cartridge (service\service.impl.ts.vsl) CAN EDIT
import { Injectable, inject } from '@angular/core';
import { Observable } from 'rxjs';
import { KycVO } from '@app/model/bw/co/roguesystems/imis/kyc/kyc-vo';
import { HttpClient } from '@angular/common/http';
import { Page } from '@app/model/page.model';
import { SearchObject } from '@app/model/search-object';

@Injectable({
  providedIn: 'root'
})
export class KycApi {
    
    protected path = '/kyc';

    private http = inject(HttpClient);

    public findById(id: number | any ): Observable<KycVO | any> {


        return this.http.get<KycVO | any>(this.path + `/${id}`);

    }

    public getAll(): Observable<KycVO[] | any[]> {


        return this.http.get<KycVO[] | any[]>(this.path);

    }

    public remove(id: number | any ): Observable<boolean | any> {


        return this.http.delete<boolean | any>(this.path + `/${id}`);

    }

    public save(kyc: KycVO | any ): Observable<KycVO | any> {


        return this.http.post<KycVO | any>(this.path, kyc);

    }

    public search(criteria: string | any ): Observable<KycVO[] | any[]> {


        return this.http.post<KycVO[] | any[]>(this.path + `/search?criteria=${criteria}`, criteria);

    }

}
