// Generated by andromda-angular cartridge (service\service.impl.ts.vsl) CAN EDIT
import { Injectable, inject } from '@angular/core';
import { Observable } from 'rxjs';
import { PolicyTypeVO } from '@app/model/bw/co/roguesystems/imis/policy/type/policy-type-vo';
import { HttpClient } from '@angular/common/http';
import { Page } from '@app/model/page.model';
import { SearchObject } from '@app/model/search-object';

@Injectable({
  providedIn: 'root'
})
export class PolicyTypeApi {
    
    protected path = '/policy/type';

    private http = inject(HttpClient);

    public findById(id: number | any ): Observable<PolicyTypeVO | any> {


        return this.http.get<PolicyTypeVO | any>(this.path + `/${id}`);

    }

    public getAll(): Observable<PolicyTypeVO[] | any[]> {


        return this.http.get<PolicyTypeVO[] | any[]>(this.path);

    }

    public remove(id: number | any ): Observable<boolean | any> {


        return this.http.delete<boolean | any>(this.path + `/${id}`);

    }

    public save(type: PolicyTypeVO | any ): Observable<PolicyTypeVO | any> {


        return this.http.post<PolicyTypeVO | any>(this.path, type);

    }

    public search(criteria: string | any ): Observable<PolicyTypeVO[] | any[]> {


        return this.http.post<PolicyTypeVO[] | any[]>(this.path + `/search?criteria=${criteria}`, criteria);

    }

}
