// Generated by andromda-angular cartridge (view\view.component.imp.ts.vsl) CAN EDIT!
import { Component } from '@angular/core';
import { PolicyDetailsComponent } from '@app/view/policy/policy-details.component';
import { PolicyDetailsVarsForm } from '@app/view/policy/policy-details.component';
import { MatRadioChange } from '@angular/material/radio';
import { MatCheckboxChange } from '@angular/material/checkbox';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { TranslateModule } from '@ngx-translate/core';
import { MaterialModule } from '@app/material.module';
import { CsvModule } from '@ctrl/ngx-csv';
import { TableComponent } from '@app/components/table/table.component';
import { PolicyEditorImplComponent } from '@app/components/policy/policy-editor-impl.component';

@Component({
  selector: 'app-policy-details',
  templateUrl: './policy-details.component.html',
  styleUrls: ['./policy-details.component.scss'],
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    TranslateModule,
    MaterialModule,
    CsvModule,
    TableComponent,
    PolicyEditorImplComponent,
  ],
})
export class PolicyDetailsImplComponent extends PolicyDetailsComponent {

    constructor() {
        super();
        this.policyApiStore.reset()
        this.success = this.policyApiStore.success;
        this.loading = this.policyApiStore.loading;
        this.error = this.policyApiStore.error;
    }

    override beforeOnInit(form: PolicyDetailsVarsForm): PolicyDetailsVarsForm{     
        return form;
    }

    doNgOnDestroy(): void {
    }
}