// Generated by andromda-angular cartridge (view\view.component.imp.ts.vsl) CAN EDIT!
import { Component } from '@angular/core';
import { PolicyViewComponent } from '@app/view/policy/policy-view.component';
import { PolicyViewVarsForm } from '@app/view/policy/policy-view.component';
import { MatRadioChange } from '@angular/material/radio';
import { MatCheckboxChange } from '@angular/material/checkbox';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { TranslateModule } from '@ngx-translate/core';
import { MaterialModule } from '@app/material.module';
import { CsvModule } from '@ctrl/ngx-csv';
import { TableComponent } from '@app/components/table/table.component';
import { SharedModule } from '@app/@shared';
import { PolicyDetailsImplComponent } from '@app/components/policy/policy-details-impl.component';
import { PolicyEditorImplComponent } from '@app/components/policy/policy-editor-impl.component';

@Component({
  selector: 'app-policy-view',
  templateUrl: './policy-view.component.html',
  styleUrls: ['./policy-view.component.scss'],
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    TranslateModule,
    SharedModule,
    MaterialModule,
    CsvModule,
    TableComponent,
    PolicyDetailsImplComponent,
    PolicyEditorImplComponent,
  ],
})
export class PolicyViewImplComponent extends PolicyViewComponent {

    constructor() {
        super();
    }

    override beforeOnInit(form: PolicyViewVarsForm): PolicyViewVarsForm{     
        return form;
    }

    doNgOnDestroy(): void {
    }
}