// Generated by andromda-angular cartridge (view\view.component.imp.ts.vsl) CAN EDIT!
import { Component } from '@angular/core';
import { SearchPoliciesComponent } from '@app/view/policy/search-policies.component';
import { SearchPoliciesVarsForm } from '@app/view/policy/search-policies.component';
import { MatRadioChange } from '@angular/material/radio';
import { MatCheckboxChange } from '@angular/material/checkbox';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { TranslateModule } from '@ngx-translate/core';
import { MaterialModule } from '@app/material.module';
import { CsvModule } from '@ctrl/ngx-csv';
import { TableComponent } from '@app/components/table/table.component';
import { PolicyEditorImplComponent } from '@app/components/policy/policy-editor-impl.component';

@Component({
  selector: 'app-search-policies',
  templateUrl: './search-policies.component.html',
  styleUrls: ['./search-policies.component.scss'],
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    TranslateModule,
    MaterialModule,
    CsvModule,
    TableComponent,
    PolicyEditorImplComponent,
  ],
})
export class SearchPoliciesImplComponent extends SearchPoliciesComponent {

    constructor() {
        super();
        this.policyApiStore.reset()
        this.success = this.policyApiStore.success;
        this.loading = this.policyApiStore.loading;
        this.error = this.policyApiStore.error;
        this.messages = this.policyApiStore.messages;
        this.policiesTablePaged = false;
        this.policiesTableSignal = this.policyApiStore.dataList;
    }

    override beforeOnInit(form: SearchPoliciesVarsForm): SearchPoliciesVarsForm{     
        return form;
    }

    doNgOnDestroy(): void {
    }

    override beforeSearchPoliciesSearch(form: any): void {
        
      this.policyApiStore.search({
        criteria: this.criteria ? this.criteria : ''
      })
    }
}