// Generated by andromda-angular cartridge (view\view.component.imp.ts.vsl) CAN EDIT!
import { Component } from '@angular/core';
import { BeneficiariesDetailsComponent } from '@app/view/policy/beneficiary/beneficiaries-details.component';
import { BeneficiariesDetailsVarsForm } from '@app/view/policy/beneficiary/beneficiaries-details.component';
import { MatRadioChange } from '@angular/material/radio';
import { MatCheckboxChange } from '@angular/material/checkbox';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { TranslateModule } from '@ngx-translate/core';
import { MaterialModule } from '@app/material.module';
import { CsvModule } from '@ctrl/ngx-csv';
import { TableComponent } from '@app/components/table/table.component';
import { BeneficiaryDetailsImplComponent } from '@app/components/policy/beneficiary/beneficiary-details-impl.component';
import { BeneficiaryEditorImplComponent } from '@app/components/policy/beneficiary/beneficiary-editor-impl.component';

@Component({
  selector: 'app-beneficiaries-details',
  templateUrl: './beneficiaries-details.component.html',
  styleUrls: ['./beneficiaries-details.component.scss'],
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    TranslateModule,
    MaterialModule,
    CsvModule,
    TableComponent,
    BeneficiaryDetailsImplComponent,
    BeneficiaryEditorImplComponent,
  ],
})
export class BeneficiariesDetailsImplComponent extends BeneficiariesDetailsComponent {

    constructor() {
        super();
        this.beneficiaryApiStore.reset()
        this.success = this.beneficiaryApiStore.success;
        this.loading = this.beneficiaryApiStore.loading;
        this.error = this.beneficiaryApiStore.error;
    }

    override beforeOnInit(form: BeneficiariesDetailsVarsForm): BeneficiariesDetailsVarsForm{     
        return form;
    }

    doNgOnDestroy(): void {
    }
}