// Generated by andromda-angular cartridge (view\view.component.imp.ts.vsl) CAN EDIT!
import { Component } from '@angular/core';
import { BeneficiaryViewComponent } from '@app/view/policy/beneficiary/beneficiary-view.component';
import { BeneficiaryViewVarsForm } from '@app/view/policy/beneficiary/beneficiary-view.component';
import { MatRadioChange } from '@angular/material/radio';
import { MatCheckboxChange } from '@angular/material/checkbox';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { TranslateModule } from '@ngx-translate/core';
import { MaterialModule } from '@app/material.module';
import { CsvModule } from '@ctrl/ngx-csv';
import { TableComponent } from '@app/components/table/table.component';
import { BeneficiaryEditorImplComponent } from '@app/components/policy/beneficiary/beneficiary-editor-impl.component';
import { BeneficiaryDetailsImplComponent } from '@app/components/policy/beneficiary/beneficiary-details-impl.component';

@Component({
  selector: 'app-beneficiary-view',
  templateUrl: './beneficiary-view.component.html',
  styleUrls: ['./beneficiary-view.component.scss'],
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    TranslateModule,
    MaterialModule,
    CsvModule,
    TableComponent,
    BeneficiaryEditorImplComponent,
    BeneficiaryDetailsImplComponent
  ],
})
export class BeneficiaryViewImplComponent extends BeneficiaryViewComponent {

    constructor() {
        super();
        this.beneficiaryApiStore.reset()
        this.success = this.beneficiaryApiStore.success;
        this.loading = this.beneficiaryApiStore.loading;
        this.error = this.beneficiaryApiStore.error;
        this.messages = this.beneficiaryApiStore.messages;

        this.route.queryParams.subscribe((params: any) => {
          if (params.id) {
            this.beneficiaryApiStore.findById(params);
          }
        });
    }

    override beforeOnInit(form: BeneficiaryViewVarsForm): BeneficiaryViewVarsForm{     
        return form;
    }

    doNgOnDestroy(): void {
    }

    override get beneficiaryViewEditId(): number {
  
      return this.beneficiaryDetails.formGroupControl.get('id')?.value;
    }
}