// Generated by andromda-angular cartridge (view\view.component.imp.ts.vsl) CAN EDIT!
import { Component } from '@angular/core';
import { EditBeneficiaryComponent } from '@app/view/policy/beneficiary/edit-beneficiary.component';
import { EditBeneficiaryVarsForm } from '@app/view/policy/beneficiary/edit-beneficiary.component';
import { MatRadioChange } from '@angular/material/radio';
import { MatCheckboxChange } from '@angular/material/checkbox';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { TranslateModule } from '@ngx-translate/core';
import { MaterialModule } from '@app/material.module';
import { CsvModule } from '@ctrl/ngx-csv';
import { TableComponent } from '@app/components/table/table.component';
import { BeneficiaryDetailsImplComponent } from '@app/components/policy/beneficiary/beneficiary-details-impl.component';
import { BeneficiaryEditorImplComponent } from '@app/components/policy/beneficiary/beneficiary-editor-impl.component';

@Component({
  selector: 'app-edit-beneficiary',
  templateUrl: './edit-beneficiary.component.html',
  styleUrls: ['./edit-beneficiary.component.scss'],
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    TranslateModule,
    MaterialModule,
    CsvModule,
    TableComponent,
    BeneficiaryDetailsImplComponent,
    BeneficiaryEditorImplComponent,
  ],
})
export class EditBeneficiaryImplComponent extends EditBeneficiaryComponent {

    constructor() {
        super();
        this.beneficiaryApiStore.reset()
        this.success = this.beneficiaryApiStore.success;
        this.loading = this.beneficiaryApiStore.loading;
        this.error = this.beneficiaryApiStore.error;
        this.messages = this.beneficiaryApiStore.messages;

        this.route.queryParams.subscribe((params: any) => {
          if (params.id) {
            this.beneficiaryApiStore.findById(params);
          }
        });
    }

    override beforeOnInit(form: EditBeneficiaryVarsForm): EditBeneficiaryVarsForm{     
        return form;
    }

    doNgOnDestroy(): void {
    }

    override beforeEditBeneficiarySave(form: any): void {
        
      form.beneficiary = { ...this.beneficiaryEditor?.formGroupControl?.value };
      this.beneficiaryApiStore.save(form);
    }

    override get editBeneficiaryViewDetailsId(): number {
      return this.beneficiaryEditor?.formGroupControl?.get('id')?.value;
    }
}