// Generated by andromda-angular cartridge (view\view.component.imp.ts.vsl) CAN EDIT!
import { Component } from '@angular/core';
import { EditLearningOutcomeComponent } from '@app/view/policy/beneficiary/edit-learning-outcome.component';
import { EditLearningOutcomeVarsForm } from '@app/view/policy/beneficiary/edit-learning-outcome.component';
import { MatRadioChange } from '@angular/material/radio';
import { MatCheckboxChange } from '@angular/material/checkbox';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { TranslateModule } from '@ngx-translate/core';
import { MaterialModule } from '@app/material.module';
import { CsvModule } from '@ctrl/ngx-csv';
import { TableComponent } from '@app/components/table/table.component';
import { SharedModule } from '@app/@shared';
import { BeneficiaryDetailsImplComponent } from '@app/components/policy/beneficiary/beneficiary-details-impl.component';
import { BeneficiaryEditorImplComponent } from '@app/components/policy/beneficiary/beneficiary-editor-impl.component';

@Component({
  selector: 'app-edit-learning-outcome',
  templateUrl: './edit-learning-outcome.component.html',
  styleUrls: ['./edit-learning-outcome.component.scss'],
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    TranslateModule,
    SharedModule,
    MaterialModule,
    CsvModule,
    TableComponent,
    BeneficiaryDetailsImplComponent,
    BeneficiaryEditorImplComponent,
  ],
})
export class EditLearningOutcomeImplComponent extends EditLearningOutcomeComponent {

    constructor() {
        super();
    }

    override beforeOnInit(form: EditLearningOutcomeVarsForm): EditLearningOutcomeVarsForm{     
        return form;
    }

    doNgOnDestroy(): void {
    }
}