// Generated by andromda-angular cartridge (view\view.component.imp.ts.vsl) CAN EDIT!
import { Component } from '@angular/core';
import { SearchBeneficiariesComponent } from '@app/view/policy/beneficiary/search-beneficiaries.component';
import { SearchBeneficiariesVarsForm } from '@app/view/policy/beneficiary/search-beneficiaries.component';
import { MatRadioChange } from '@angular/material/radio';
import { MatCheckboxChange } from '@angular/material/checkbox';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { TranslateModule } from '@ngx-translate/core';
import { MaterialModule } from '@app/material.module';
import { CsvModule } from '@ctrl/ngx-csv';
import { TableComponent } from '@app/components/table/table.component';
import { BeneficiaryEditorImplComponent } from '@app/components/policy/beneficiary/beneficiary-editor-impl.component';

@Component({
  selector: 'app-search-beneficiaries',
  templateUrl: './search-beneficiaries.component.html',
  styleUrls: ['./search-beneficiaries.component.scss'],
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    TranslateModule,
    MaterialModule,
    CsvModule,
    TableComponent,
    BeneficiaryEditorImplComponent,
  ],
})
export class SearchBeneficiariesImplComponent extends SearchBeneficiariesComponent {

    constructor() {
        super();
        this.beneficiaryApiStore.reset()
        this.success = this.beneficiaryApiStore.success;
        this.loading = this.beneficiaryApiStore.loading;
        this.error = this.beneficiaryApiStore.error;
        this.beneficiariesTablePaged = false;
        this.beneficiariesTableSignal = this.beneficiaryApiStore.dataList;
    }

    override beforeOnInit(form: SearchBeneficiariesVarsForm): SearchBeneficiariesVarsForm{     
        return form;
    }

    doNgOnDestroy(): void {
    }

    override beforeSearchBeneficiariesSearch(form: any): void {
        this.beneficiaryApiStore.search({
          criteria: this.criteria ? this.criteria : ''
        })
    }
}