// Generated by andromda-angular cartridge (view\view.component.imp.ts.vsl) CAN EDIT!
import { Component } from '@angular/core';
import { CustomerDetailsComponent } from '@app/view/customer/customer-details.component';
import { CustomerDetailsVarsForm } from '@app/view/customer/customer-details.component';
import { MatRadioChange } from '@angular/material/radio';
import { MatCheckboxChange } from '@angular/material/checkbox';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { TranslateModule } from '@ngx-translate/core';
import { MaterialModule } from '@app/material.module';
import { CsvModule } from '@ctrl/ngx-csv';
import { TableComponent } from '@app/components/table/table.component';
import { CustomerEditorImplComponent } from '@app/components/customer/customer-editor-impl.component';

@Component({
  selector: 'app-customer-details',
  templateUrl: './customer-details.component.html',
  styleUrls: ['./customer-details.component.scss'],
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    TranslateModule,
    MaterialModule,
    CsvModule,
    TableComponent,
    CustomerEditorImplComponent,
  ],
})
export class CustomerDetailsImplComponent extends CustomerDetailsComponent {

    constructor() {
        super();
        this.customerApiStore.reset()
        this.success = this.customerApiStore.success;
        this.loading = this.customerApiStore.loading;
        this.error = this.customerApiStore.error;
    }

    override beforeOnInit(form: CustomerDetailsVarsForm): CustomerDetailsVarsForm{     
        return form;
    }

    doNgOnDestroy(): void {
    }
}