// Generated by andromda-angular cartridge (view\view.component.imp.ts.vsl) CAN EDIT!
import { Component } from '@angular/core';
import { EditCustomerComponent } from '@app/view/customer/edit-customer.component';
import { EditCustomerVarsForm } from '@app/view/customer/edit-customer.component';
import { MatRadioChange } from '@angular/material/radio';
import { MatCheckboxChange } from '@angular/material/checkbox';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { TranslateModule } from '@ngx-translate/core';
import { MaterialModule } from '@app/material.module';
import { CsvModule } from '@ctrl/ngx-csv';
import { TableComponent } from '@app/components/table/table.component';
import { SharedModule } from '@app/@shared';
import { CustomerEditorImplComponent } from '@app/components/customer/customer-editor-impl.component';
import { CustomerDetailsImplComponent } from '@app/components/customer/customer-details-impl.component';

@Component({
  selector: 'app-edit-customer',
  templateUrl: './edit-customer.component.html',
  styleUrls: ['./edit-customer.component.scss'],
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    TranslateModule,
    SharedModule,
    MaterialModule,
    CsvModule,
    TableComponent,
    CustomerEditorImplComponent,
    CustomerDetailsImplComponent,
  ],
})
export class EditCustomerImplComponent extends EditCustomerComponent {

    constructor() {
        super();
    }

    override beforeOnInit(form: EditCustomerVarsForm): EditCustomerVarsForm{     
        return form;
    }

    doNgOnDestroy(): void {
    }
}