// Generated by andromda-angular cartridge (view\view.component.imp.ts.vsl) CAN EDIT!
import { Component } from '@angular/core';
import { SearchCustomersComponent } from '@app/view/customer/search-customers.component';
import { SearchCustomersVarsForm } from '@app/view/customer/search-customers.component';
import { MatRadioChange } from '@angular/material/radio';
import { MatCheckboxChange } from '@angular/material/checkbox';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { TranslateModule } from '@ngx-translate/core';
import { MaterialModule } from '@app/material.module';
import { CsvModule } from '@ctrl/ngx-csv';
import { TableComponent } from '@app/components/table/table.component';
import { CustomerEditorImplComponent } from '@app/components/customer/customer-editor-impl.component';

@Component({
  selector: 'app-search-customers',
  templateUrl: './search-customers.component.html',
  styleUrls: ['./search-customers.component.scss'],
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    TranslateModule,
    MaterialModule,
    CsvModule,
    TableComponent,
    CustomerEditorImplComponent,
  ],
})
export class SearchCustomersImplComponent extends SearchCustomersComponent {

    constructor() {
        super();
        this.customerApiStore.reset()
        this.success = this.customerApiStore.success;
        this.loading = this.customerApiStore.loading;
        this.error = this.customerApiStore.error;
        this.customersTablePaged = false;
        this.customersTableSignal = this.customerApiStore.dataPage;
    }

    override beforeOnInit(form: SearchCustomersVarsForm): SearchCustomersVarsForm{     
        return form;
    }

    doNgOnDestroy(): void {
    }

    override beforeSearchCustomersSearch(form: any): void {
        this.customerApiStore.search({
          criteria: this.criteria ? this.criteria : ''
        })
    }
}