// Generated by andromda-angular cartridge (view\view.component.imp.ts.vsl) CAN EDIT!
import { Component } from '@angular/core';
import { EditRelationshipComponent } from '@app/view/relationship/edit-relationship.component';
import { EditRelationshipVarsForm } from '@app/view/relationship/edit-relationship.component';
import { MatRadioChange } from '@angular/material/radio';
import { MatCheckboxChange } from '@angular/material/checkbox';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { TranslateModule } from '@ngx-translate/core';
import { MaterialModule } from '@app/material.module';
import { CsvModule } from '@ctrl/ngx-csv';
import { TableComponent } from '@app/components/table/table.component';
import { RelationshipEditorImplComponent } from '@app/components/relationship/relationship-editor-impl.component';
import { RelationshipDetailsImplComponent } from '@app/components/relationship/relationship-details-impl.component';

@Component({
  selector: 'app-edit-relationship',
  templateUrl: './edit-relationship.component.html',
  styleUrls: ['./edit-relationship.component.scss'],
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    TranslateModule,
    MaterialModule,
    CsvModule,
    TableComponent,
    RelationshipEditorImplComponent,
    RelationshipDetailsImplComponent,
  ],
})
export class EditRelationshipImplComponent extends EditRelationshipComponent {
  constructor() {
    super();
  }

  override beforeOnInit(form: EditRelationshipVarsForm): EditRelationshipVarsForm {
    return form;
  }

  doNgOnDestroy(): void {}

  override beforeEditRelationshipSave(form: any): void {
      
    form.relationship = { ...this.relationshipEditor?.relationshipEditorForm?.value }
    this.relationshipApiStore.save(form);
  }
}
