// Generated by andromda-angular cartridge (view\view.component.imp.ts.vsl) CAN EDIT!
import { Component } from '@angular/core';
import { RelationshipViewComponent } from '@app/view/relationship/relationship-view.component';
import { RelationshipViewVarsForm } from '@app/view/relationship/relationship-view.component';
import { MatRadioChange } from '@angular/material/radio';
import { MatCheckboxChange } from '@angular/material/checkbox';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { TranslateModule } from '@ngx-translate/core';
import { MaterialModule } from '@app/material.module';
import { CsvModule } from '@ctrl/ngx-csv';
import { TableComponent } from '@app/components/table/table.component';
import { RelationshipEditorImplComponent } from '@app/components/relationship/relationship-editor-impl.component';
import { RelationshipDetailsImplComponent } from '@app/components/relationship/relationship-details-impl.component';

@Component({
  selector: 'app-relationship-view',
  templateUrl: './relationship-view.component.html',
  styleUrls: ['./relationship-view.component.scss'],
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    TranslateModule,
    MaterialModule,
    CsvModule,
    TableComponent,
    RelationshipEditorImplComponent,
    RelationshipDetailsImplComponent
  ],
})
export class RelationshipViewImplComponent extends RelationshipViewComponent {

    constructor() {
        super();
        this.relationshipApiStore.reset()
        this.success = this.relationshipApiStore.success;
        this.loading = this.relationshipApiStore.loading;
        this.error = this.relationshipApiStore.error;
        this.messages = this.relationshipApiStore.messages;

        this.route.queryParams.subscribe((params: any) => {
          if (params.id) {
            this.relationshipApiStore.findById(params);
          }
        });
    }

    override beforeOnInit(form: RelationshipViewVarsForm): RelationshipViewVarsForm{     
        return form;
    }

    doNgOnDestroy(): void {
    }

  override get relationshipViewEditId(): number {

    return this.relationshipDetails.formGroupControl.get('id')?.value;
  }
}