// Generated by andromda-angular cartridge (view\view.component.imp.ts.vsl) CAN EDIT!
import { Component } from '@angular/core';
import { RelationshipsDetailsComponent } from '@app/view/relationship/relationships-details.component';
import { RelationshipsDetailsVarsForm } from '@app/view/relationship/relationships-details.component';
import { MatRadioChange } from '@angular/material/radio';
import { MatCheckboxChange } from '@angular/material/checkbox';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { TranslateModule } from '@ngx-translate/core';
import { MaterialModule } from '@app/material.module';
import { CsvModule } from '@ctrl/ngx-csv';
import { TableComponent } from '@app/components/table/table.component';
import { RelationshipEditorImplComponent } from '@app/components/relationship/relationship-editor-impl.component';
import { RelationshipDetailsImplComponent } from '@app/components/relationship/relationship-details-impl.component';

@Component({
  selector: 'app-relationships-details',
  templateUrl: './relationships-details.component.html',
  styleUrls: ['./relationships-details.component.scss'],
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    TranslateModule,
    MaterialModule,
    CsvModule,
    TableComponent,
    RelationshipEditorImplComponent,
    RelationshipDetailsImplComponent,
  ],
})
export class RelationshipsDetailsImplComponent extends RelationshipsDetailsComponent {

    constructor() {
        super();
    }

    override beforeOnInit(form: RelationshipsDetailsVarsForm): RelationshipsDetailsVarsForm{     
        return form;
    }

    doNgOnDestroy(): void {
    }
}