// Generated by andromda-angular cartridge (view\view.component.imp.ts.vsl) CAN EDIT!
import { Component } from '@angular/core';
import { SearchRelationshipComponent } from '@app/view/relationship/search-relationship.component';
import { SearchRelationshipVarsForm } from '@app/view/relationship/search-relationship.component';
import { MatRadioChange } from '@angular/material/radio';
import { MatCheckboxChange } from '@angular/material/checkbox';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { TranslateModule } from '@ngx-translate/core';
import { MaterialModule } from '@app/material.module';
import { CsvModule } from '@ctrl/ngx-csv';
import { TableComponent } from '@app/components/table/table.component';
import { RelationshipEditorImplComponent } from '@app/components/relationship/relationship-editor-impl.component';

@Component({
  selector: 'app-search-relationship',
  templateUrl: './search-relationship.component.html',
  styleUrls: ['./search-relationship.component.scss'],
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    TranslateModule,
    MaterialModule,
    CsvModule,
    TableComponent,
    RelationshipEditorImplComponent,
  ],
})
export class SearchRelationshipImplComponent extends SearchRelationshipComponent {

    constructor() {
        super();
        this.relationshipApiStore.reset()
        this.success = this.relationshipApiStore.success;
        this.loading = this.relationshipApiStore.loading;
        this.error = this.relationshipApiStore.error;
        this.messages = this.relationshipApiStore.messages;
        this.relationshipsTablePaged = false;
        this.relationshipsTableSignal = this.relationshipApiStore.dataList;
    }

    override beforeOnInit(form: SearchRelationshipVarsForm): SearchRelationshipVarsForm{     
        return form;
    }

    doNgOnDestroy(): void {
    }

    override beforeSearchRelationshipSearch(form: any): void {
        
      this.relationshipApiStore.search({
        criteria: this.criteria ? this.criteria : ''
      });
    }
}