// Generated by andromda-angular cartridge (controller\controller.impl.ts.vsl) Can Modify
import { Injectable } from '@angular/core';
import { PolicyController } from '@app/controller/policy/policy-controller';

@Injectable()
export class PolicyControllerImpl extends PolicyController {

    constructor() {
        super();
    }

}
