// Generated by hibernate/SpringHibernateDaoImpl.vsl in andromda-spring-cartridge on $springUtils.date.
// license-header java merge-point
/**
 * This is only generated once! It will never be overwritten.
 * You can (and have to!) safely modify it by hand.
 */
package bw.co.roguesystems.imis.policy;

import bw.co.roguesystems.imis.customer.CustomerRepository;
import bw.co.roguesystems.imis.policy.beneficiary.BeneficiaryRepository;
import bw.co.roguesystems.imis.policy.type.PolicyTypeRepository;
import org.springframework.stereotype.Repository;

/**
 * @see Policy
 */
@Repository("policyDao")
public class PolicyDaoImpl
    extends PolicyDaoBase
{
    
    public PolicyDaoImpl(
        PolicyTypeRepository policyTypeRepository,
        CustomerRepository customerRepository,
        BeneficiaryRepository beneficiaryRepository,
        PolicyRepository policyRepository
    ) {

        super(
            policyTypeRepository,
            customerRepository,
            beneficiaryRepository,
            policyRepository
        );
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public void toPolicyVO(
        Policy source,
        PolicyVO target)
    {
        // TODO verify behavior of toPolicyVO
        super.toPolicyVO(source, target);
        // WARNING! No conversion for target.startDate (can't convert source.getStartDate():java.util.Date to java.util.Date
        // WARNING! No conversion for target.policyType (can't convert source.getPolicyType():bw.co.roguesystems.imis.policy.type.PolicyType to bw.co.roguesystems.imis.policy.type.PolicyTypeVO
        // WARNING! No conversion for target.customer (can't convert source.getCustomer():bw.co.roguesystems.imis.customer.Customer to bw.co.roguesystems.imis.customer.CustomerVO
        // WARNING! No conversion for target.endDate (can't convert source.getEndDate():java.util.Date to java.util.Date
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PolicyVO toPolicyVO(final Policy entity)
    {
        // TODO verify behavior of toPolicyVO
        return super.toPolicyVO(entity);
    }

    /**
     * Retrieves the entity object that is associated with the specified value object
     * from the object store. If no such entity object exists in the object store,
     * a new, blank entity is created
     */
    private Policy loadPolicyFromPolicyVO(PolicyVO policyVO)
    {
        if (policyVO.getId() == null)
        {
            return  Policy.Factory.newInstance();
        }
        else
        {
            return this.load(policyVO.getId());
        }
    }

    /**
     * {@inheritDoc}
     */
    public Policy policyVOToEntity(PolicyVO policyVO)
    {
        // TODO verify behavior of policyVOToEntity
        Policy entity = this.loadPolicyFromPolicyVO(policyVO);
        this.policyVOToEntity(policyVO, entity, true);
        return entity;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public void policyVOToEntity(
        PolicyVO source,
        Policy target,
        boolean copyIfNull)
    {
        // TODO verify behavior of policyVOToEntity
        super.policyVOToEntity(source, target, copyIfNull);
        // No conversion for target.startDate (can't convert source.getStartDate():java.util.Date to java.util.Date
        // No conversion for target.endDate (can't convert source.getEndDate():java.util.Date to java.util.Date
    }
}