// Generated by andromda-angular cartridge (controller\controller.impl.ts.vsl) Can Modify
import { Injectable } from '@angular/core';
import { BenefitController } from '@app/controller/policy/type/benefits/benefit-controller';

@Injectable()
export class BenefitControllerImpl extends BenefitController {

    constructor() {
        super();
    }

}
