// Generated by andromda-angular cartridge (controller\controller.impl.ts.vsl) Can Modify
import { Injectable } from '@angular/core';
import { vo } from '@app/controller/policy/type/benefits/vo';

@Injectable()
export class VoImpl extends vo {

    constructor() {
        super();
    }

}
