// Generated by andromda-angular cartridge (view\view.component.imp.ts.vsl) CAN EDIT!
import { Component } from '@angular/core';
import { PolicyTypeViewComponent } from '@app/view/policy/type/policy-type-view.component';
import { PolicyTypeViewVarsForm } from '@app/view/policy/type/policy-type-view.component';
import { MatRadioChange } from '@angular/material/radio';
import { MatCheckboxChange } from '@angular/material/checkbox';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { TranslateModule } from '@ngx-translate/core';
import { MaterialModule } from '@app/material.module';
import { CsvModule } from '@ctrl/ngx-csv';
import { TableComponent } from '@app/components/table/table.component';
import { PolicyTypeEditorImplComponent } from '@app/components/policy/type/policy-type-editor-impl.component';
import { PolicyTypeDetailsImplComponent } from '@app/components/policy/type/policy-type-details-impl.component';

@Component({
  selector: 'app-policy-type-view',
  templateUrl: './policy-type-view.component.html',
  styleUrls: ['./policy-type-view.component.scss'],
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    TranslateModule,
    MaterialModule,
    CsvModule,
    TableComponent,
    PolicyTypeEditorImplComponent,
    PolicyTypeDetailsImplComponent
  ],
})
export class PolicyTypeViewImplComponent extends PolicyTypeViewComponent {

    constructor() {
        super();
        this.policyTypeApiStore.reset()
        this.success = this.policyTypeApiStore.success;
        this.loading = this.policyTypeApiStore.loading;
        this.error = this.policyTypeApiStore.error;
        this.messages = this.policyTypeApiStore.messages;

        this.route.queryParams.subscribe((params: any) => {
          if (params.id) {
            this.policyTypeApiStore.findById(params);
          }
        });
    }

    override beforeOnInit(form: PolicyTypeViewVarsForm): PolicyTypeViewVarsForm{     
        return form;
    }

    doNgOnDestroy(): void {
    }

    override get policyTypeViewEditId(): number {
  
      return this.policyTypeDetails.formGroupControl.get('id')?.value;
    }
}