// Generated by andromda-angular cartridge (view\view.component.imp.ts.vsl) CAN EDIT!
import { Component } from '@angular/core';
import { TopicViewComponent } from '@app/view/policy/type/topic-view.component';
import { TopicViewVarsForm } from '@app/view/policy/type/topic-view.component';
import { MatRadioChange } from '@angular/material/radio';
import { MatCheckboxChange } from '@angular/material/checkbox';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { TranslateModule } from '@ngx-translate/core';
import { MaterialModule } from '@app/material.module';
import { CsvModule } from '@ctrl/ngx-csv';
import { TableComponent } from '@app/components/table/table.component';
import { SharedModule } from '@app/@shared';
import { PolicyTypeEditorImplComponent } from '@app/components/policy/type/policy-type-editor-impl.component';
import { PolicyTypeDetailsImplComponent } from '@app/components/policy/type/policy-type-details-impl.component';

@Component({
  selector: 'app-topic-view',
  templateUrl: './topic-view.component.html',
  styleUrls: ['./topic-view.component.scss'],
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    TranslateModule,
    SharedModule,
    MaterialModule,
    CsvModule,
    TableComponent,
    PolicyTypeEditorImplComponent,
    PolicyTypeDetailsImplComponent,
  ],
})
export class TopicViewImplComponent extends TopicViewComponent {

    constructor() {
        super();
    }

    override beforeOnInit(form: TopicViewVarsForm): TopicViewVarsForm{     
        return form;
    }

    doNgOnDestroy(): void {
    }
}