// Generated by andromda-angular cartridge (controller\controller.impl.ts.vsl) Can Modify
import { Injectable } from '@angular/core';
import { PolicyTypeController } from '@app/controller/policy/type/policy-type-controller';

@Injectable()
export class PolicyTypeControllerImpl extends PolicyTypeController {

    constructor() {
        super();
    }

}
