// Generated by andromda-angular cartridge (controller\controller.impl.ts.vsl) Can Modify
import { Injectable } from '@angular/core';
import { BeneficiaryController } from '@app/controller/policy/beneficiary/beneficiary-controller';

@Injectable()
export class BeneficiaryControllerImpl extends BeneficiaryController {

    constructor() {
        super();
    }

}
